Criando servico para cadastro de autor
luanmelo/deveficiente-casadocodigo pull request #1
Opened 2020-01-21 02:25 UTC by luanmelo

Tentando seguir seus pilares de desenvolvimento....rs

2020-01-21 08:56 UTC, asouza requested changes
Aqui você escreveu de um jeito que realmente eu gosto muito, simples e direto ao ponto.

2020-01-21 08:56 UTC, asouza commented on casadocodigo/src/main/java/br/com/deveficiente/casadocodigo/autor/Autor.java
> +	public void setNome(String nome) {
*A complicação do nosso é código é proporcional a complicação da nossa feature. Quanto mais simples, melhor.*

Neste exato momento ainda não precisamos nem de getter nem de setter para o autor, minha sugestão é tirar aqui. Tenta garantir que todo código que você escreve está sendo usando por alguma outra parte do sistema.

2020-01-21 08:56 UTC, asouza commented on casadocodigo/src/main/java/br/com/deveficiente/casadocodigo/autor/NovoAutorForm.java
> +	public void setNome(String nome) {
Aqui só um comentário para exemplificar o anterior. Os getters e setters aqui existem por conta do Spring e seu mecanismo de preencher um objeto em função do formulário. Só que eu acabei de perceber uma coisa: estamos fazendo uma api. E o estado do formulário, hipoteticamente, já estaria sendo mantido pelo cliente. Acho que nem precisa dos getters aqui, só dos setters :). Experimenta? Inclusive eu teria que mudar isso em alguns códigos meus :).

2020-01-22 02:39 UTC, luanmelo commented
Fiz o merge porque como a mudança era mais simples e precisava pra da continuidade no outro card, acredito que não precisaria avaliar novamente as mudanças. Como que ficará quando precisar avaliar novo PR de uma mudança? Ajustamos e esperamos você aprovar o PR para dá continuidade em outro card?

2020-01-22 02:39 UTC, merged

2020-01-22 02:54 UTC, asouza commented
Opa, idealmente é melhor esperar o review sim :). Mas por outro lado você tinha razão e ta tudo certo. Joga duro!